export const projectsClasses = {
  page: "min-h-screen pt-[80px] sm:pt-[98px] md:pt-[98px] pb-16 p-2 sm:p-4 md:p-8 lg:px-24 font-mono",
  container: "max-w-3xl mx-auto space-y-4 sm:space-y-6 md:space-y-8",
  intro: "space-y-2",
  title: "text-3xl md:text-4xl font-bold",
  subtitle: "text-muted-foreground",
  tabs: "flex flex-wrap justify-center items-center gap-2 sm:gap-3 md:gap-4 mt-4",
  tabButton: "px-3 sm:px-4 md:px-5 py-2 rounded text-xs sm:text-sm md:text-base transition-colors whitespace-nowrap",
  card: "p-3 sm:p-4 md:p-6 bg-card text-card-foreground border-2 border-gray-300 dark:border-gray-700 rounded-lg shadow-md",
  cardHeader: "flex justify-between items-start mb-3",
  cardTitle: "text-lg sm:text-xl md:text-2xl font-semibold",
  statusChip: "flex items-center gap-2 px-3 py-1 border-2 border-gray-300 dark:border-gray-600 rounded-lg bg-background",
  mediaFrame: "w-full rounded-md bg-muted/20 border border-gray-300 dark:border-gray-700 flex items-center justify-center p-2 mt-2",
  tags: "flex flex-wrap gap-2 mt-3",
  tag: "bg-background border border-foreground/20 text-foreground rounded-full px-3 py-1 select-none cursor-default transition-transform duration-150 ease-out hover:scale-105 hover:bg-foreground/10",
  points: "mt-2 text-muted-foreground list-disc pl-5",
  links: "flex space-x-4 mt-4",
  section: "space-y-4",
  sectionTitle: "text-3xl font-semibold",
}
